wavefrontHQ/wavefront-sdk-java

pom.xml
To avoid the build warnings:
`[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.wavefront:java-sdk:jar:0.9.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 44, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.`
=> Set version for maven-compiler-plugin.

pom.xml
This change is protect against making a FAT JAR is future. But has no effect now.
=> Use includes on shaded plugin instead of excludes.

src/main/java/com/wavefront/sdk/direct/ingestion/DataIngesterService.java
If the WF Proxy (or a separate data ingester service that forwards WF
metrics) is hosted on a custom path; the DataIngesterService now
supports that.
=> DataIngesterService supports a custom path

src/main/java/com/wavefront/sdk/direct/ingestion/DataIngesterService.java
When reading data to gzip and send to the endpoint, keep reading in 4kb chunks. If the data
is not exactly 4k aligned then in the last iteration, allocate the buffer for only that many
bytes that remains in the stream.
I setup a proxy locally and changed the Main.java to send 10000 points to it.
```java
private static void sendMetricViaDirectIngestion(
WavefrontDirectIngestionClient wavefrontDirectIngestionClient) throws IOException {
/*
* Wavefront Metrics Data format
* <metricName> <metricValue> [<timestamp>] source=<source> [pointTags]
*
* Example: "new-york.power.usage 42422 1533529977 source=localhost datacenter=dc1"
*/
Map<String, String> tags = new HashMap<String, String>() {{
put("datacenter", "dc1");
}};
for (int i = 0; i < 10000; i ++) { …
```
=> Read data based on available bytes in the stream

src/main/java/com/wavefront/sdk/direct/ingestion/WavefrontDirectIngestionClient.java, src/main/java/com/wavefront/sdk/entities/metrics/WavefrontMetricSender.java, src/main/java/com/wavefront/sdk/proxy/WavefrontProxyClient.java
This enables clients to leverage the compression and batching features
already provided by the SDK without forcing them to supply individual
metric details separately (metric name, value, point-tags, etc.).
A client can send a metric point already in raw WF format.
=> Wavefront Metric Sender supports sending raw WF-formatted strings

src/main/java/com/wavefront/sdk/common/annotation/NonNullApi.java
Hi,
Currently, there are `@NonNull` and `@Nullable` in sdk, but annotating `@NonNull` is just half of the nullability enforcement.
You need to add package level annotation to make the semantics of default parameters and return values to be non-null under the package.
This PR just adds `@NonNullApi` annotation.
To enforce nullability, you need to add `package-info.java` and annotate the package declaration with `@NonNullApi`. This sets the default semantics to non-null, then annotate `@Nullable` for things that can be null.
FYI, If you want to support Kotlin, this null-safety is important.
=> Add @NonNullApi to set package level non-null semantics

src/main/java/com/wavefront/sdk/common/Utils.java, src/test/java/com/wavefront/sdk/common/UtilsTest.java
- For metric name / source / key, applying same rule as proxy checking logic (replace all illegal char with `-`).
- For tag value, only remove leading and trailing spaces and process quotes if is needed.
=> Allow whitespace for tag value and Applying proxy rule to metrics name

src/main/java/com/wavefront/sdk/common/Utils.java, src/main/java/com/wavefront/sdk/common/application/HeartbeaterService.java, src/main/java/com/wavefront/sdk/common/metrics/WavefrontSdkMetricsRegistry.java, src/main/java/com/wavefront/sdk/direct/ingestion/WavefrontDirectIngestionClient.java, src/main/java/com/wavefront/sdk/proxy/WavefrontProxyClient.java, src/test/java/com/wavefront/sdk/proxy/ProxyTest.java
This PR is intended to close issue #108.
A call to Sender::close() could cause non-deamon threads to be left running preventing the process from exiting. This was caused by two separate race conditions.
1) It was possible to call the various send* functions on a closed Sender. This caused the new ```ReconnectingSocket``` objects to be created, but since the cancel on their timers was supposed to have already been called when closing the senders, the timers were never cancelled. Addressed this by maintaining a flag on the sender indicating if it's closed and by throwing exceptions if operations were attempted on a closed sender.
2) Various Executors were created throughout the code. When a sender is closed, all these executors were terminated using the ```shutdownNow()``` method. This …
=> Addressed various race conditions causing thread leakage

pom.xml, src/main/java/com/wavefront/sdk/common/Constants.java, src/main/java/com/wavefront/sdk/common/Utils.java, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/main/java/com/wavefront/sdk/direct/ingestion/WavefrontDirectIngestionClient.java, src/main/java/com/wavefront/sdk/proxy/WavefrontProxyClient.java, src/main/resources/build.properties, src/test/java/com/wavefront/sdk/common/UtilsTest.java
We will be emitting the below metric from each client:
For version 2.6.1 , we will emit metric value as `2.0601`. The charts will need to be set as a single stat with a precision of 4 decimals.
~sdk.*.version 2.0601 source=<hostip>
=> Add build.version info to sdk metrics.

pom.xml, src/main/java/com/wavefront/sdk/common/Constants.java, src/main/java/com/wavefront/sdk/common/Utils.java, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/main/resources/META-INF/wavefront-sdk-java/build.properties, src/main/resources/build.properties, src/test/java/com/wavefront/sdk/common/UtilsTest.java
This change Includes : 
1. A new ns separated resource file "build.properties" to store the version info
2. Utility methods to get Resources/version info/ version gauge values reported etc. 
Tested with slim/uber jar and version info is retrieved correctly as long as resources are included in the jar.
=>  Incude a namespace separated build.properties files 

pom.xml, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/test/java/com/wavefront/sdk/common/clients/WavefrontClientTest.java
* Add validateEndpoint method to WavefrontClient.Builder
* add javadoc
=> Add validateEndpoint method to WavefrontClient.Builder (#169)

pom.xml
This removes shaded dependencies from the SDK, enabling users to update them indepdent of our release cadence when necessary.
This also updates dependencies to the latest versions:
- jackson-databind 2.12.4
- guava 30.1.1-jre
- junit-jupiter-api 5.7.2
- easymock 4.3
Skipped updating to t-digest 3.3 since it caused non-trivial failures in `WavefrontHistogramImplTest`. There wasn't a changelog for 3.3 describing why the behavior may have changed.
=> Unshade and update dependencies

pom.xml, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/test/java/com/wavefront/sdk/common/clients/WavefrontClientFactoryTest.java, src/test/java/com/wavefront/sdk/common/clients/WavefrontClientTest.java, src/test/java/com/wavefront/sdk/common/clients/service/ReportingServiceTest.java
- Pull out WavefrontClientFactory and ReportingService tests
- Use ParameterizedTests from JUnit 5
- Use simple ServerSocket instead of HTTPServer
- Fix exception in validateEndpoint() signature
=> Refactor WavefrontClientTest.java

pom.xml, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/main/java/com/wavefront/sdk/common/clients/service/ReportingService.java, src/test/java/com/wavefront/sdk/common/clients/WavefrontClientTest.java
Background: we recommend that Distributed Tracing customers have span-level RED metrics computed by sending spans to the Wavefront Proxy's `customTracingListenerPorts` (30001 by default). `WavefrontProxyClient` in this SDK allowed configuring a separate port for spans, but was deprecated in #127.
Until Wavefront Proxy's default listener on port 2878 can also generate span-level RED metrics, we should allow `WavefrontClient` to specify a custom port when sending spans.
Also, backfilled tests for WavefrontClient.
=> WavefrontClient can send spans to different port than metrics

pom.xml
This is a breaking API change, removing the following packages:
- `com.wavefront.java_sdk.com.google`
- `com.wavefront.java_sdk.com.tdunning.math`
As such, it warrants releasing a new major version of this SDK: 3.0.
=> Unshade guava and t-digest dependencies to release v3.0.0

src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/main/java/com/wavefront/sdk/common/logging/MessageDedupingLogger.java, src/main/java/com/wavefront/sdk/direct/ingestion/WavefrontDirectIngestionClient.java, src/test/java/com/wavefront/sdk/common/logging/MessageDedupingLoggerTest.java
Add support in MessageDepupingLogger to include a Throwable forincluding a stack trace in log output.
Used new logger method in:
- WavefrontClient
- WavefrontDirectIngestionClient
- Already included stack trace: WavefrontProxyClient
**Testing Notes**
Manually tested with test harness app:
```
Sent tracing span: 'getAllUsers' to proxy
Jun 08, 2022 3:48:49 PM com.wavefront.sdk.common.clients.WavefrontClient run
WARNING: Unable to report to Wavefront cluster: 
java.io.IOException: attempt to flush closed sender
at com.wavefront.sdk.common.clients.WavefrontClient.flush(WavefrontClient.java:632)
at com.wavefront.sdk.common.clients.WavefrontClient.run(WavefrontClient.java:619)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at …
```
=> [MONIT-29250] Include stack traces in `run()` methods

src/main/java/com/wavefront/sdk/common/Constants.java, src/main/java/com/wavefront/sdk/common/Utils.java, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/main/java/com/wavefront/sdk/entities/tracing/SpanLogsDTO.java, src/test/java/com/wavefront/sdk/common/UtilsTest.java, src/test/java/com/wavefront/sdk/common/clients/WavefrontClientTest.java
The `_spanSecondaryId` field wasn't included on span logs, meaning that links to span logs in the UI weren't working in certain cases for spring boot apps. I only implemented this feature in `WavefrontClient` (not the deprecated DI and Proxy clients).
Also added FINE-level logging of Wavefront data in`WavefrontClient` when the following methods are invoked:
- sendDistribution
- sendEvent
- sendFormattedMetric
- sendLog
- sendMetric
- sendSpan
- sendSpanLogs
=> Fix _spanSecondaryId for span logs & add fine-level logging

src/main/java/com/wavefront/sdk/Main.java, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/main/java/com/wavefront/sdk/common/clients/service/ReportingService.java
When using just `ex.getMessage()` the error message would look like:
>  Unable to obtain status code from the Wavefront service at http://foo.bar/report?f=trace due to: foo.bar
Without the exception's class name it can be hard to know the real error. Now it looks like:
>  Unable to obtain status code from the Wavefront service at http://foo.bar/report?f=trace due to: java.net.UnknownHostException: foo.bar
Also, some small improvements to the Main.java demo so not include the deprecated WavefrontSenders.
=> Improve log messages from `ReportingService`

src/main/java/com/wavefront/sdk/Main.java, src/main/java/com/wavefront/sdk/common/clients/WavefrontClient.java, src/main/java/com/wavefront/sdk/common/clients/service/ReportingService.java
Use `WavefrontClient.Builder#reportingServiceLogSuppressTimeSeconds()`
Fixes https://github.com/wavefrontHQ/wavefront-sdk-java/issues/206
Co-authored by : Glenn Oppegard <goppegard@vmware.com>
=> Make suppressing logger configurable for ReportingService

pom.xml
Reverts wavefrontHQ/wavefront-sdk-java#260
It causes the release process for v3.2.0 of the SDK to fail in Jenkins.
=> Revert "Bump maven-javadoc-plugin from 3.4.1 to 3.5.0"

src/main/java/com/wavefront/sdk/common/clients/service/token/CSPTokenService.java, src/test/java/com/wavefront/sdk/common/clients/service/CSPTokenServiceTest.java
per discussion with Anil on slack
=> Removed unnecessary scope check

src/main/java/com/wavefront/sdk/common/Utils.java, src/main/java/com/wavefront/sdk/common/logging/DelegatingLogger.java, src/main/java/com/wavefront/sdk/common/logging/MessageDedupingLogger.java, src/main/java/com/wavefront/sdk/common/logging/MessageSuppressingLogger.java, src/test/java/com/wavefront/sdk/common/logging/DelegatingLoggerTest.java, src/test/java/com/wavefront/sdk/common/logging/MessageDedupingLoggerTest.java
- Estimate `StringBuilder` capacity in `tracingSpanToLineData()` to reduce memory allocations
- Return early from loggers based on `Level`
[K8SSASS-2541]
=> Optimize tracingSpanToLineData and loggers
